[package]
name = "roaring-bitmap"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[lib]
name = "roaring_bitmap"
path = "lib.rs"

[dependencies]

[dev-dependencies]
